### PR TITLE
Temporary fix for streaming body responses - load body to BytesIO

### PR DESCRIPTION
**Pull request by oselivanov**
…ect.

### CODE REVIEW

**Comment by oselivanov** [comment]
Hm, looks like version in master already fixed. Closing as invalid for now.

**Comment by oselivanov** [comment]
I've ran wrong test, actually it's still broken, so my fix is valid.

**Comment by oselivanov** [comment]
This quickfix breaks API BTW.

    body = await obj['Body'].read()

will become 

   body = obj['Body'].read()

I'll fix it today if I have a minute.

**Comment by oselivanov** [comment]
Done. I've amended commit.

**Comment by cbrichford** [comment]
I believe #19 ( which was just merge ) fixes this issue.

**Pull request closed without merging**
